server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    # eureka client向eureka server发送心跳的时间间隔，默认30秒，将此值改小可解决eureka注册慢的问题
    lease-renewal-interval-in-seconds: 3
    # 续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 3

#注意：在Finchley.M9版本（写这段代码是为最新版本）里，Feign默认是不开启hystrix的，需要手动开启，否则容断器不生效
feign:
  hystrix:
    enabled: true

# 说明：请务必注意，在Spring Cloud Dalston中，Feign默认是不开启Hystrix的。
# 因此，如使用Dalston请务必额外设置属性：feign.hystrix.enabled=true，否则断路器不会生效。
# 而，Spring Cloud Angel/Brixton/Camden中，Feign默认都是开启Hystrix的。无需设置该属性。


management:
  endpoints:
    web:
      exposure:
        #springboot2.0中，默认只开放health和当info,
        #详情请参见：https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-endpoints
        #访问路径为：http://localhost:8010/actuator
        include: '*'
