spring:
  application:
    name: config-center

  # git管理配置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dhappy05/spring-cloud/    #配置git仓库位置
          search-paths: spring-cloud-config-demo/config-repo       #配置仓库路径下的相对搜索位置，可以配置多个
          username: username       #访问git仓库的用户名
          password: password       #访问git仓库的用户密码

server:
  port: 7001

#配置文件的命名格式为：{application}-{profile}.properties
#启动服务端后可通过http://localhost:7001/configcenter/prod/master来测试
#其中configcenter对应到配置文件名中的application,prod对应到配置文件的profile，master对应到git的分支